---
# handlers

- name: restart iwd
  systemd:
    name: iwd.service
    state: restarted

- name: restart bluetooth
  systemd:
    name: bluetooth.service
    state: restarted

- name: restart tlp
  systemd:
    name: tlp.service
    state: restarted
