all:
  children:
    gateway:
      hosts:
        auganite.wg.jaantoots.org:
          wg0_ipv4: 172.24.128.1/24
          wg0_ipv6: fdf6:8288:f5ec:8001::1/56
          endpoint: auganite.tll.jaantoots.org
          public_endpoint: auganite.jaantoots.org
    storage:
      hosts:
        box.wg.jaantoots.org:
          wg0_ipv4: 172.24.128.2/32
          wg0_ipv6: fdf6:8288:f5ec:8002::1/64
          endpoint: box.tll.jaantoots.org
    workstations:
      hosts:
        falstaff.wg.jaantoots.org:
          wg0_ipv4: 172.24.128.4/32
          wg0_ipv6: fdf6:8288:f5ec:8004::1/64
          endpoint: falstaff.tll.jaantoots.org
          multilib: true
    laptops:
      hosts:
        caracal.wg.jaantoots.org:
          wg0_ipv4: 172.24.128.3/32
          wg0_ipv6: fdf6:8288:f5ec:8003::1/64
        gpd.wg.jaantoots.org:
          wg0_ipv4: 172.24.128.5/32
          wg0_ipv6: fdf6:8288:f5ec:8005::1/64
  vars:
    ansible_user: ansible
    wg0_subnets:
    - 172.24.128.0/24
    - fdf6:8288:f5ec:8000::/56
