---
# setup all systems

- name: apply basic configuration
  hosts: all
  become: yes
  vars_files:
  - vars.yml
  roles:
  - base

- name: apply gateway configuration
  hosts: gateway
  become: yes
  vars_files:
  - vars.yml
  roles:
  - wg-server
  - pacman-server

- name: apply storage configuration
  hosts: storage
  become: yes
  vars_files:
  - vars.yml
  roles:
  - wg-storage
  - pacman-client

- name: apply workstation configuration
  hosts: workstations
  become: yes
  vars_files:
  - vars.yml
  roles:
  - wg-storage
  - pacman-server
  - graphical

- name: apply laptop configuration
  hosts: laptops
  become: yes
  vars_files:
  - vars.yml
  roles:
  - wg-client
  - pacman-client
  - graphical
  - laptop
