---
# setup all systems

- name: apply basic configuration
  hosts: all
  become: yes
  vars_files:
  - vars.yml
  roles:
  - base

- name: apply gateway configuration
  hosts: gateway
  become: yes
  vars_files:
  - vars.yml
  roles:
  - gateway

- name: apply graphical configuration
  hosts: graphical
  become: yes
  vars_files:
  - vars.yml
  roles:
  - client
  - graphical

- name: apply laptop configuration
  hosts: laptops
  become: yes
  vars_files:
  - vars.yml
  roles:
  - laptop
