---
# set up graphical and interactive tools

- name: install interactive tools
  pacman:
    name:
    - isync
    - keybase
    - khal
    - khard
    - msmtp
    - msmtp-mta
    - mutt-ics
    - neomutt
    - notmuch
    - pass
    - pass-otp
    - rclone
    - urlview
    - vdirsyncer
    - vifm
    - wireless_tools

- name: add urlview configuration
  copy:
    src: system.urlview
    dest: /etc/urlview/system.urlview

- name: install graphical packages
  pacman:
    name:
    - alsa-utils
    - awesome-terminal-fonts
    - browserpass
    - browserpass-firefox
    - caprine
    - chrome-token-signing
    - chromium
    - dunst
    - esteidpkcs11loader
    - feh
    - firefox
    - firejail
    - gnu-free-fonts
    - gnumeric
    - guvcview
    - i3-wm
    - i3lock-color
    - i3status
    - imagemagick
    - kitty
    - libnotify
    - libreoffice-fresh
    - mesa-demos
    - mpv
    - noto-fonts
    - noto-fonts-cjk
    - noto-fonts-emoji
    - noto-fonts-extra
    - pdfjs
    - playerctl
    - pulseaudio
    - pulseaudio-alsa
    - qdigidoc4
    - qrencode
    - qutebrowser
    - riot-desktop
    - rofi
    - scrot
    - signal-desktop
    - spotify
    - sxiv
    - tigervnc
    - ttf-croscore
    - ttf-inconsolata
    - ttf-liberation
    - x11vnc
    - xbindkeys
    - xdotool
    - xorg-server
    - xorg-xdpyinfo
    - xorg-xev
    - xorg-xinit
    - xorg-xinput
    - xorg-xprop
    - xss-lock
    - xterm
    - zathura
    - zathura-djvu
    - zathura-pdf-mupdf
    - zathura-ps
    - zulip-desktop

- name: configure typematic delay and rate as Xserver options
  copy:
    src: xserverrc
    dest: /etc/X11/xinit/xserverrc

- name: add input device configuration for xorg
  copy:
    src: "{{ item }}"
    dest: /etc/X11/xorg.conf.d/
  loop:
  - 29-mouse.conf
  - 30-touchpad.conf

- name: create dmenu symlink to rofi
  file:
    src: /usr/bin/rofi
    dest: /usr/local/bin/dmenu
    state: link
    force: yes

- name: install dev packages
  pacman:
    name:
    - ansible
    - ansible-lint
    - aurutils
    - aws-cli
    - backblaze-b2
    - devtools
    - gnuplot
    - go
    - graphviz
    - mypy
    - namcap
    - opencv
    - opencv-samples
    - pandoc
    - python-black
    - python-h5py
    - python-matplotlib
    - python-pylint
    - python-virtualenv
    - terraform
    - tesseract
    - tesseract-data
    - texlive-lang
    - texlive-most

- name: install container tools
  pacman:
    name:
    - binfmt-qemu-static
    - docker
    - docker-compose
    - lxc
    - ovmf
    - qemu
    - qemu-arch-extra
    - qemu-user-static

- name: start and enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
  - pcscd.socket
