---
# handlers

- name: reload sshd
  systemd:
    name: sshd.service
    state: reloaded

- name: restart networkd
  systemd:
    name: systemd-networkd.service
    state: restarted

- name: restart resolved
  systemd:
    name: systemd-resolved.service
    state: restarted
