---
# laptop

- name: install laptop packages
  pacman:
    name:
    - acpilight
    - bluez-utils
    - iw
    - iwd
    - powertop
    - pulseaudio-bluetooth
    - tlp

- name: add iwd configuration
  copy:
    src: iwd/
    dest: /etc/iwd/
  notify:
  - restart iwd

- name: add network configuration
  copy:
    src: "{{ item }}"
    dest: /etc/systemd/network/
  loop:
  - 79-wlan.link
  - 80-wlan.network
  notify:
  - restart networkd

- name: add bluetooth configuration
  copy:
    src: bluetooth/
    dest: /etc/bluetooth/
  notify:
  - restart bluetooth

- name: add user to video group for backlight
  user:
    name: "{{ user.username }}"
    append: yes
    groups: video

- name: add tlp configuration
  copy:
    src: tlp
    dest: /etc/default/tlp
  notify:
  - restart tlp

- name: start and enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
  - bluetooth.service
  - iwd.service
  - tlp.service

- name: enable services
  systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
  - tlp-sleep.service
