---
# laptop

- name: install laptop packages
  pacman:
    name:
    - acpilight
    - bluez
    - bluez-utils
    - iw
    - iwd
    - powertop
    - tlp

- name: add user to video group for backlight
  user:
    name: "{{ username }}"
    append: yes
    groups: video

- name: add tlp configuration
  copy:
    src: tlp
    dest: /etc/default/tlp
  notify:
  - restart tlp

- name: start and enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
  - iwd.service
  - tlp.service

- name: enable services
  systemd:
    name: "{{ item }}"
    enabled: yes
  loop:
  - tlp-sleep.service
