---
# storage tasks

- name: add nftables configuration
  copy:
    src: nftables.conf
    dest: /etc/nftables.conf
  notify:
  - reload nftables

- name: add WireGuard configuration
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/network/{{ item }}"
  loop:
  - 50-wg0.netdev
  - 50-wg0.network
  notify:
  - restart networkd

- name: start and enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
  - nftables.service
